apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: install-and-test
      taskRef:
        name: npm-install-and-test
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build-image
      runAfter: [install-and-test]
      taskRef:
        name: buildah
      params:
        - name: IMAGE
          value: us.icr.io/tax-calculator-sn/tax-app:latest
      workspaces:
        - name: source
          workspace: shared-workspace
